### ISSUE TITLE
Image is enlarged not extended

### ISSUE THREAD

**Issue by daverdalas** [netcell/nine-patch-phaser-plugin#1]
Hey, I am trying to use your library using this image: http://imgur.com/UnO2hY4,WbZ9H6X
This is my code:

```
preload: function () {
   this.load.image('dialogPatter', 'assets/images/dialog.png');
 },

create: function () {
    this.game.cache.addNinePatch('dialog', 'dialogPatter', 0, 10, 10, 10, 20);
    var image = new Phaser.NinePatchImage(this.game, 10, 10, 'dialog');
    image.targetWidth  = 400;
    image.targetHeight  = 400;
    image.UpdateImageSizes();
 }
```

Picture after the code looks stretched (http://imgur.com/CW5ZZya) as if we have done normally and not using ninepatch. Probably I am doing something wrong, so I wanted to ask for help :)

**Comment by netcell** [comment]
You have to change the params `10, 10, 10, 20` on the line `this.game.cache.addNinePatch('dialog', 'dialogPatter', 0, 10, 10, 10, 20);` to match your image :) Please read the readme for more detail.

Sadly I didn't write an intelligent module to automatically generate such values for you, though I might write a tool for this in the future

**Comment by daverdalas** [comment]
My mistake I thought that the values have to be given in the order like in css starting from the top. Btw. thank you for your help :)
